# System params
system_name: "C"
elements: ["C"]
atom_counts: [24]
# blocks - list of integers of length number of atoms, each atom is represented by its elemnt number
blocks: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
# volume- intiial volume of unit cell. 
volume: 450
# ratio_of_covalent_radii - ratio of covalent radii for the system
ratio_of_covalent_radii: 0.4
# fitler_comparison_data_for_n_atoms - maximum number of atoms for reference structures for plotting
fitler_comparison_data_for_n_atoms: 24

# Type of start generator (random / pyxtal)
start_generator: "pyxtal"

# Variation operator params
operator_probabilities: [0.0, 0, 10.0, 0.0]

# BD params
n_behavioural_descriptor_dimensions: 2
bd_minimum_values: [0, 4]
bd_maximum_values: [5.5, 535]

# Fitness params
reference_point: [0, 0]
fitness_min_values: [4, 0] # for plotting
fitness_max_values: [11, 1.2]