# System params
system_name: "Si"
blocks: [14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14]
volume: 450
ratio_of_covalent_radii: 0.4
fitler_comparison_data_for_n_atoms: 24

# Initialisation params
start_generator: "pyxtal"

# Variation operator params
operator_probabilities: [0.0, 0, 10.0, 0.0]
batch_size: 100

# BD params
n_behavioural_descriptor_dimensions: 2
bd_minimum_values: [0, 25]
bd_maximum_values: [7, 220]

# Fitness params
fitness_min_max_values: [3, 5.5]

