# System params
system_name: "Si"
elements: ["Si"]
atom_counts: [24]
blocks: [14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14]
volume: 450
ratio_of_covalent_radii: 0.4
fitler_comparison_data_for_n_atoms: 24

# Initialisation params
start_generator: "pyxtal"

# Variation operator params
operator_probabilities: [0.0, 0, 10.0, 0.0]

# BD params
n_behavioural_descriptor_dimensions: 2
bd_minimum_values: [0, 25]
bd_maximum_values: [4, 70]

# Fitness params
reference_point: [0, 0]
fitness_min_values: [3, 0]
fitness_max_values: [7, 1.2]
