# System params
system_name: "SiC"
elements: ["Si", "C"]
atom_counts: [12, 12]
blocks: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14]
volume: 450
ratio_of_covalent_radii: 0.4
fitler_comparison_data_for_n_atoms: 24

# Initialisation params
start_generator: "pyxtal"

# Variation operator params
operator_probabilities: [0.0, 0, 5.0, 5.0]

# BD params
n_behavioural_descriptor_dimensions: 2
bd_minimum_values: [0.2, 170]
bd_maximum_values: [0.9, 185]

# Fitness params
reference_point: [0, 0]
fitness_min_values: [5.8, 0]
fitness_max_values: [10, 1.2]
