# System params
system_name: "SiO2"
elements: ["Si", "O"]
atom_counts: [8, 16]
blocks: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 14, 14, 14, 14, 14, 14, 14, 14]
volume: 450
ratio_of_covalent_radii: 0.4
fitler_comparison_data_for_n_atoms: 24

# Initialisation params
start_generator: "pyxtal"

# Variation operator params
operator_probabilities: [0.0, 0, 5.0, 5.0]

# BD params
n_behavioural_descriptor_dimensions: 2
bd_minimum_values: [0, 25]
bd_maximum_values: [6.8, 225]

# Fitness params
reference_point: [0, 0]
fitness_min_values: [2.5, 0]
fitness_max_values: [12, 2.5]