# System params
system_name: "SiO2"
blocks: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 14, 14, 14, 14, 14, 14, 14, 14]
volume: 450
ratio_of_covalent_radii: 0.4
fitler_comparison_data_for_n_atoms: 24

# Initialisation params
start_generator: "pyxtal"

# Variation operator params
operator_probabilities: [0.0, 0, 5.0, 5.0]
batch_size: 10

# BD params
n_behavioural_descriptor_dimensions: 2
bd_minimum_values: [0, 25]
bd_maximum_values: [6.8, 222]

# Fitness params
reference_point: [0, 0]
fitness_min_max_values: [6.3, 8.3]
