hydra:
    run:
        dir: ./output/${system.system_name}/${algo.algo_name}/${now:%Y-%m-%d_%H%M%S}

# Defaults
defaults:
    - algo: mome
    - system: TiO2
experiment_tag: ${now:%Y-%m-%d_%H%M%S}
random_seed: 42
number_of_threads: 16

# CVT params
number_of_niches: 200
maximum_evaluations: 5000
cvt_samples: 25000

# MOME parameters 
max_front_size: 10

# Initialisation parameters
random_init: 0.005
random_init_batch: 100

# Algorithm running parameters
batch_size: 100
dump_period: 1000
parallel: True
cvt_use_cache: True
seed: False

# Materials parameters
relaxation_probability: 0
behavioural_descriptors: ["band_gap","shear_modulus"]
number_of_relaxation_steps: 100
filter_starting_Structures: 24
profiling: False
force_threshold: True

## Other algorithm params
force_threshold_exp_fmax: 1.0
fmax_threshold: 0.2
normalise_bd: true

alternative_operators: null
compute_gradients: False
dqd_learning_rate: 0.0001
from_archive_path: null
